# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procdure',
            fields=[
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('basic_class', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('step_name', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Company')),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=50)),
                ('group', models.CharField(default='User', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='work_steam',
            fields=[
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Company')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Procdure')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('work_level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='work_steam',
            name='woker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.worker'),
        ),
        migrations.AddField(
            model_name='score',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.worker'),
        ),
    ]
