# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='', max_length=10, verbose_name='\u7f16\u53f7')),
                ('name', models.CharField(default='', max_length=10, verbose_name='\u59d3\u540d')),
                ('typ', models.CharField(default='', max_length=10, verbose_name='\u53d8\u66f4\u7c7b\u578b')),
                ('remark', models.TextField(default='', verbose_name='\u53d8\u66f4\u8bf4\u660e')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 2, 3, 0, 9, 6, 114000), verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
    ]
