# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 22, 37, 11, 680000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_place',
            field=models.CharField(max_length=50, verbose_name='\u7c4d\u8d2f'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sn',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u5e8f\u5217'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_level',
            field=models.IntegerField(verbose_name='\u7ea7\u522b'),
        ),
    ]
